# Copia este archivo a `.streamlit/secrets.toml` y completa tus claves.
# Este archivo de ejemplo sí puede versionarse; el real secrets.toml está ignorado en .gitignore

FINNHUB_API_KEY = "YOUR_FINNHUB_KEY_HERE"
PERPLEXITY_API_KEY = "YOUR_PERPLEXITY_KEY_HERE"
PPLX_ENDPOINT = "https://api.perplexity.ai/chat/completions"